all: MinMin MinMIN MINMin MINMIN
    
MinMin: MinMin.c
	gcc -o MinMin MinMin.c
    
MinMIN: MinMIN.c
	gcc -o MinMIN MinMIN.c
    
MINMin: MINMin.c
	gcc -o MINMin MINMin.c
    
MINMIN: MINMIN.c
	gcc -o MINMIN MINMIN.c
    
clean: 
	rm MinMin MinMIN MINMin MINMIN
