all: MinMin MinMIN MINMin MINMIN
    
MinMin: MinMin.c
	gcc -std=c99 -o MinMin MinMin.c
    
MinMIN: MinMIN.c
	gcc -std=c99 -o MinMIN MinMIN.c
    
MINMin: MINMin.c
	gcc -std=c99 -o MINMin MINMin.c
    
MINMIN: MINMIN.c
	gcc -std=c99 -o MINMIN MINMIN.c
    
clean: 
	rm MinMin MinMIN MINMin MINMIN
