#!/bin/bash

sudo qmgr -c "set node node02.cluster.fing properties = all"
sudo qmgr -c "set node node02.cluster.fing properties += cpu"
sudo qmgr -c "set node node02.cluster.fing properties += cpu8"
sudo qmgr -c "set node node02.cluster.fing properties += ram8"
sudo qmgr -c "set node node02.cluster.fing properties += class0"

sudo qmgr -c "set node node03.cluster.fing properties = all"
sudo qmgr -c "set node node03.cluster.fing properties += cpu"
sudo qmgr -c "set node node03.cluster.fing properties += cpu8"
sudo qmgr -c "set node node03.cluster.fing properties += ram8"
sudo qmgr -c "set node node03.cluster.fing properties += class0"

sudo qmgr -c "set node node04.cluster.fing properties = all"
sudo qmgr -c "set node node04.cluster.fing properties += cpu"
sudo qmgr -c "set node node04.cluster.fing properties += cpu8"
sudo qmgr -c "set node node04.cluster.fing properties += ram8"
sudo qmgr -c "set node node04.cluster.fing properties += class0"

sudo qmgr -c "set node node05.cluster.fing properties = all"
sudo qmgr -c "set node node05.cluster.fing properties += cpu"
sudo qmgr -c "set node node05.cluster.fing properties += cpu8"
sudo qmgr -c "set node node05.cluster.fing properties += ram8"
sudo qmgr -c "set node node05.cluster.fing properties += class0"

sudo qmgr -c "set node node06.cluster.fing properties = all"
sudo qmgr -c "set node node06.cluster.fing properties += cpu"
sudo qmgr -c "set node node06.cluster.fing properties += cpu8"
sudo qmgr -c "set node node06.cluster.fing properties += ram8"
sudo qmgr -c "set node node06.cluster.fing properties += class0"

sudo qmgr -c "set node node07.cluster.fing properties = all"
sudo qmgr -c "set node node07.cluster.fing properties += cpu"
sudo qmgr -c "set node node07.cluster.fing properties += cpu8"
sudo qmgr -c "set node node07.cluster.fing properties += ram8"
sudo qmgr -c "set node node07.cluster.fing properties += class0"

sudo qmgr -c "set node node08.cluster.fing properties = all"
sudo qmgr -c "set node node08.cluster.fing properties += cpu"
sudo qmgr -c "set node node08.cluster.fing properties += cpu8"
sudo qmgr -c "set node node08.cluster.fing properties += ram8"
sudo qmgr -c "set node node08.cluster.fing properties += class0"

sudo qmgr -c "set node node09.cluster.fing properties = all"
sudo qmgr -c "set node node09.cluster.fing properties += cpu"
sudo qmgr -c "set node node09.cluster.fing properties += cpu8"
sudo qmgr -c "set node node09.cluster.fing properties += ram8"
sudo qmgr -c "set node node09.cluster.fing properties += class0"

sudo qmgr -c "set node node20.cluster.fing properties = all"
sudo qmgr -c "set node node20.cluster.fing properties += cpu"
sudo qmgr -c "set node node20.cluster.fing properties += cpu8"
sudo qmgr -c "set node node20.cluster.fing properties += ram24"
sudo qmgr -c "set node node20.cluster.fing properties += class1"

sudo qmgr -c "set node node21.cluster.fing properties = all"
sudo qmgr -c "set node node21.cluster.fing properties += cpu"
sudo qmgr -c "set node node21.cluster.fing properties += cpu8"
sudo qmgr -c "set node node21.cluster.fing properties += ram24"
sudo qmgr -c "set node node21.cluster.fing properties += class1"

sudo qmgr -c "set node node22.cluster.fing properties = all"
sudo qmgr -c "set node node22.cluster.fing properties += cpu"
sudo qmgr -c "set node node22.cluster.fing properties += cpu8"
sudo qmgr -c "set node node22.cluster.fing properties += ram24"
sudo qmgr -c "set node node22.cluster.fing properties += class1"

sudo qmgr -c "set node node23.cluster.fing properties = all"
sudo qmgr -c "set node node23.cluster.fing properties += cpu"
sudo qmgr -c "set node node23.cluster.fing properties += cpu8"
sudo qmgr -c "set node node23.cluster.fing properties += ram24"
sudo qmgr -c "set node node23.cluster.fing properties += class1"

sudo qmgr -c "set node node20.cluster.fing np = 8"
sudo qmgr -c "set node node21.cluster.fing np = 8"
sudo qmgr -c "set node node22.cluster.fing np = 8"
sudo qmgr -c "set node node23.cluster.fing np = 8"

sudo qmgr -c "set node tesla.cluster.fing properties = all"
sudo qmgr -c "set node tesla.cluster.fing properties += gpu"
sudo qmgr -c "set node tesla.cluster.fing properties += gpu4"
sudo qmgr -c "set node tesla.cluster.fing properties += ram48"

sudo qmgr -c "set node node30.cluster.fing properties = all"
sudo qmgr -c "set node node30.cluster.fing properties += cpu"
sudo qmgr -c "set node node30.cluster.fing properties += cpu24"
sudo qmgr -c "set node node30.cluster.fing properties += ram24"
sudo qmgr -c "set node node30.cluster.fing properties += class2"

sudo qmgr -c "set node node31.cluster.fing properties = all"
sudo qmgr -c "set node node31.cluster.fing properties += cpu"
sudo qmgr -c "set node node31.cluster.fing properties += cpu24"
sudo qmgr -c "set node node31.cluster.fing properties += ram24"
sudo qmgr -c "set node node31.cluster.fing properties += class2"

sudo qmgr -c "set node node32.cluster.fing properties = all"
sudo qmgr -c "set node node32.cluster.fing properties += cpu"
sudo qmgr -c "set node node32.cluster.fing properties += cpu24"
sudo qmgr -c "set node node32.cluster.fing properties += ram24"
sudo qmgr -c "set node node32.cluster.fing properties += class2"

sudo qmgr -c "set node node33.cluster.fing properties = all"
sudo qmgr -c "set node node33.cluster.fing properties += cpu"
sudo qmgr -c "set node node33.cluster.fing properties += cpu24"
sudo qmgr -c "set node node33.cluster.fing properties += ram72"
sudo qmgr -c "set node node33.cluster.fing properties += class3"

sudo qmgr -c "set node node34.cluster.fing properties = all"
sudo qmgr -c "set node node34.cluster.fing properties += cpu"
sudo qmgr -c "set node node34.cluster.fing properties += cpu24"
sudo qmgr -c "set node node34.cluster.fing properties += ram72"
sudo qmgr -c "set node node34.cluster.fing properties += class3"

sudo qmgr -c "set node node35.cluster.fing properties = all"
sudo qmgr -c "set node node35.cluster.fing properties += cpu"
sudo qmgr -c "set node node35.cluster.fing properties += cpu24"
sudo qmgr -c "set node node35.cluster.fing properties += ram72"
sudo qmgr -c "set node node35.cluster.fing properties += class3"

sudo qmgr -c "set node node36.cluster.fing properties = all"
sudo qmgr -c "set node node36.cluster.fing properties += cpu"
sudo qmgr -c "set node node36.cluster.fing properties += cpu24"
sudo qmgr -c "set node node36.cluster.fing properties += ram72"
sudo qmgr -c "set node node36.cluster.fing properties += class3"

sudo qmgr -c "set node node37.cluster.fing properties = all"
sudo qmgr -c "set node node37.cluster.fing properties += cpu"
sudo qmgr -c "set node node37.cluster.fing properties += cpu24"
sudo qmgr -c "set node node37.cluster.fing properties += ram72"
sudo qmgr -c "set node node37.cluster.fing properties += class3"

sudo qmgr -c "set node node38.cluster.fing properties = quick"
sudo qmgr -c "set node node38.cluster.fing properties += cpu"
sudo qmgr -c "set node node38.cluster.fing properties += cpu24"
sudo qmgr -c "set node node38.cluster.fing properties += ram72"
sudo qmgr -c "set node node38.cluster.fing properties += class3"
