all: p512 p1024 p2048

p512: pPALS.2D.MaS.pool.sem.512.c
	gcc pPALS.2D.MaS.pool.sem.512.c -o palsRuso.512 -lpthread -O3

p1024: pPALS.2D.MaS.pool.sem.1024.c
	gcc pPALS.2D.MaS.pool.sem.1024.c -o palsRuso.1024 -lpthread -O3

p2048: pPALS.2D.MaS.pool.sem.2048.c
	gcc pPALS.2D.MaS.pool.sem.2048.c -o palsRuso.2048 -lpthread -O3
