set -x

HOME_DIR=/home/santiago/google-hosting/itu-maestria/svn/trunk/aedb-mls

cd $HOME_DIR
#make clean
#make

#SEED=$RANDOM
SEED=1
ITERATIONS=20
THREADS=2
SIMULATIONS=6
DENSITY=25
RESET=5
MIN_COVERAGE=5
ALPHA=0.2
ELITE=1
INIT_FUNCTION=2
REPORT_START=5
REPORT_EVERY=14

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME_DIR/ns3Files
time(mpiexec -np 2 bin/mls $SEED $ITERATIONS $THREADS $SIMULATIONS $DENSITY $RESET $MIN_COVERAGE $ALPHA $ELITE $INIT_FUNCTION $REPORT_START $REPORT_EVERY)
